/**
 * Audible result for the provisioning and assembly stations.
 *
 * The operator is looking at the part, not at the screen: a result that is
 * only visual is a result they can miss while their hands are busy. A short
 * tone reports the outcome before it becomes a wrongly labelled part.
 *
 * Generated by the browser, so there is no audio file to load and nothing to
 * install. Two clearly different tones: a high short one for accepted, a low
 * double one for refused — distinguishable without looking up, and without
 * relying on colour.
 */

let context: AudioContext | null = null;

function getContext(): AudioContext | null {
  if (typeof window === "undefined") return null;
  if (context) return context;

  const Ctor =
    window.AudioContext ??
    (window as unknown as { webkitAudioContext?: typeof AudioContext })
      .webkitAudioContext;

  if (!Ctor) return null;
  context = new Ctor();
  return context;
}

function tone(frequency: number, startAt: number, duration: number) {
  const ctx = getContext();
  if (!ctx) return;

  const oscillator = ctx.createOscillator();
  const gain = ctx.createGain();

  oscillator.frequency.value = frequency;
  oscillator.type = "sine";

  // Ramped rather than switched, so the tone does not click.
  gain.gain.setValueAtTime(0, ctx.currentTime + startAt);
  gain.gain.linearRampToValueAtTime(0.18, ctx.currentTime + startAt + 0.01);
  gain.gain.linearRampToValueAtTime(
    0,
    ctx.currentTime + startAt + duration
  );

  oscillator.connect(gain);
  gain.connect(ctx.destination);
  oscillator.start(ctx.currentTime + startAt);
  oscillator.stop(ctx.currentTime + startAt + duration + 0.02);
}

/** Accepted: one short high note. */
export function soundAccepted() {
  try {
    tone(880, 0, 0.12);
  } catch {
    // Audio is a second channel, never the only one. A browser that blocks
    // it must not break the action that just succeeded.
  }
}

/** Refused: two low notes, clearly not the accepted sound. */
export function soundRefused() {
  try {
    tone(300, 0, 0.16);
    tone(220, 0.2, 0.26);
  } catch {
    // Same.
  }
}
